name: Audio Settings Tests

on: workflow_dispatch

jobs:
  test:
    runs-on: ${{ matrix.os }}
    matrix: { os: windows-latest, python-version: '3.9' }

    steps:
      - name: Checkout destination repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          pip install -e .

      - name: Run tests - frequency_response_pure_wf
        run: |
          pytest -v tests/test_audio_settings.py::test_frequency_response_pure_wf

      - name: output results file
        run: |
          cat xray-report.xml

#      - name: Export results to Xray
#        uses: mikepenz/xray-action@v3.1.1
#        with:
#          username: ${{ secrets.XRAY_CLIENT_ID }}
#          password: ${{ secrets.XRAY_CLIENT_SECRET }}
#          xrayBaseUrl: ${{ secrets.XRAY_API_BASE_URL }}
#          testFormat: "junit"
#          testPaths: "**/test-results/*.xml"
#          projectKey: "AS"
#          testExecKey: "AS-19"
